project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - project-log.qmd
    - wikidata.qmd
    - ausstellung-joar-nango.qmd
    - wikidata-item.ipynb

website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: ausstellung-joar-nango.qmd
        text: Ausstellung
      - href: wikidata-item.ipynb
        text: Item Profile
author:
  name: "Erfan Sattarvand"
  orcid: "0009-0001-8865-3721"

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
